vim.keymap.set("n", "<leader>q", function() vim.diagnostic.setqflist() end, { desc = "Quickfix list" })
vim.keymap.set("n", "<leader>l", function() vim.diagnostic.setloclist() end, { desc = "Location list" })

vim.keymap.set("n", "<leader>n", "<cmd>enew<cr>", { desc = "New buffer" })
vim.keymap.set("n", "<leader>d", "<cmd>bd<cr>", { desc = "Delete buffer" })
vim.keymap.set("n", "<leader>T", "<cmd>tabnew<cr>", { desc = "New tab" })
vim.keymap.set("n", "<leader>C", "<cmd>tabclose<cr>", { desc = "Close tab" })

vim.keymap.set("n", "<leader>w", "<c-w>", { desc = "+window" })
vim.keymap.set("n", "<leader>wv", "<cmd>wincmd v<cr><cmd>wincmd w<cr>", { desc = "Split vertically" })
vim.keymap.set("n", "<leader>ws", "<cmd>wincmd s<cr><cmd>wincmd w<cr>", { desc = "Split horizontally" })

vim.keymap.set("n", "<leader>]", "<cmd>bnext<cr>", { desc = "Next buffer" })
vim.keymap.set("n", "<leader>[", "<cmd>bprevious<cr>", { desc = "Previous buffer" })
vim.keymap.set("n", "<tab>", "<cmd>tabnext<cr>", { desc = "Next tab" })
vim.keymap.set("n", "<s-tab>", "<cmd>tabprevious<cr>", { desc = "Previous tab" })
vim.keymap.set("n", "<c-d>", "<c-d>zz", { desc = "Down" })
vim.keymap.set("n", "<c-u>", "<c-u>zz", { desc = "Up" })
vim.keymap.set("n", "n", "nzzzv", { desc = "Next match" })
vim.keymap.set("n", "N", "Nzzzv", { desc = "Previous match" })
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("n", "J", "mzJ`z", { desc = "Join lines" })
vim.keymap.set("n", "s", "<cmd>set invspell<cr>")
vim.keymap.set("n", "<leader>p", "\"+p")
vim.keymap.set("n", "<leader>P", "\"+P")
vim.keymap.set({ "n", "v" }, "<leader>y", "\"+y")
vim.keymap.set({ "n", "v" }, "<leader>Y", "\"+Y")
vim.keymap.set("v", "<leader>d", "\"_d")
vim.keymap.set("v", "<leader>D", "\"_D")
vim.keymap.set("v", "J", ":m \'>+1<cr>gv=gv")
vim.keymap.set("v", "K", ":m \'<-2<cr>gv=gv")
vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "k", "gk")
vim.keymap.set("n", "0", "g0")
vim.keymap.set("n", "$", "g$")

vim.keymap.set("i", "<c-h>", "<left>")
vim.keymap.set("i", "<c-j>", "<down>")
vim.keymap.set("i", "<c-k>", "<up>")
vim.keymap.set("i", "<c-l>", "<right>")
